# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check pm2 and node version
        run: |
          pm2 -v
          node -v

      - name: 'Kill all running pm2 processes'
        run: pm2 kill

      - name: 'Git pull the latest code'
        run: git pull

      - name: 'Check Current Directory'
        run: |
          echo $PWD
          ls -la

      - name: 'Install the dependencies'
        run: |
          rm -rf node_modules package-lock.json
          npm install

  start:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - name: 'Check Current Directory'
        run: |
          echo $PWD
          ls -la

      - name: 'Start & Save the PM2 action'
        run: pm2 startOrRestart ecosystem.config.json --name "handyman" && pm2 save

      - run: pm2 list